### ISSUE TITLE
Tenda A6 supported?

### ISSUE THREAD

**Issue by probonopd** [JiapengLi/OpenWrt-RT5350#1]
The Tenda A6 is a very cheap (USD 15 shipped, e.g., on Aliexpress) router with onboard USB, WLAN and Ethernet, powered by the RT5350 chip. According to http://wikidevi.com/wiki/Tenda_A6 it has 4 MB flash and 32 MB RAM. Is this supported?

**Comment by JiapengLi** [comment]
Not sure about this but may be. This router seems do not have a USB master port, so i think it may not be funny to run openwrt on it.

**Comment by rogerpueyo** [comment]
Check http://wiki.openwrt.org/toh/tenda/a6

**Comment by kthur** [comment]
Are there any changes in A6?
When I compile it with A6 patch, it occurs build error cause of A6.dts

**Comment by fragtion** [comment]
Hi all

Sorry for bumping old thread, but please see the following resources as they pertain to topic of issue

https://github.com/openwrt/openwrt/pull/2988

https://github.com/fragtion/openwrt-hardware/tree/master/tenda-a6

Regards
