### ISSUE TITLE
Flashing MPR-A1

### ISSUE THREAD

**Issue by zjean** [JiapengLi/OpenWrt-RT5350#2]
Hi,
I am trying to flash the Hame MPR A1, but can't get it to work. When I follow your guide, on Windows, and try to reset the device, the blue led is not blinking. So the actual flash process will not start I think.
Could you advise me?

**Comment by JiapengLi** [comment]
The reamdme on my github is a legacy way to install OpenWrt to MPR-A1, now
you can checkout the latest trunk of OpenWrt and build it for MPR-A1,
choose  then use initram format firmware flash it from web upgrade
interface. Refer to MPR-A2 wiki to flash it.

Jiapeng

2013/9/15 zjean notifications@github.com

**Comment by JiapengLi** [comment]
http://wiki.openwrt.org/toh/hame/mpr-a2

Difference of MPR-A2 and MPR-A1 is the flash size and SDRAM size.

2013/9/15 Jiapeng Li gapleehit@gmail.com

**Comment by zjean** [comment]
Hi, I managed to build the initram firmware like outlined in the wiki page of the MPR A2, but cannot upload it on the web interface: It tells me that the firmware is invalid. Could that be sth about the compression of the ramdisk? The menuconfig shows different options for the compression, and it does not default to None.

**Comment by JiapengLi** [comment]
Sorry i never test this feature, maybe you can ask this in OpenWrt mail list or forum. I think you need to know the firmware version of your mpr-a1 and tell it to the openwrt guys who have the same device.
Maybe the firmware need to be encrypted first before use webUI to flash it.

The other device HLK-RM04 which is also a RT5350 router, use some encrypt algorithm to check the firmware.
May be MPR-A1 also use some algorithm, just guess. 

If i have enough time, i'll help to test and see if the MPR-A1 can be flashed with webUI.
